### PR TITLE
Changed Twig function class to a non-abstract one

### PR DESCRIPTION
**Pull request by chrislind**
Need to make use of the Twig_SimpleFunction which extends of Twig_Function as you can't instantiate an abstract class.

### CODE REVIEW

**Comment by gchtr** [comment]
Hey @chrislind 

Thanks for checking out the integration and for this pull request! I think what you ran into is an error that [appears in Timber as well](https://github.com/timber/timber/pull/1641).

So before pulling this in, I’d like you to check if it works if we’d use the [class that Timber provides](https://github.com/timber/timber/blob/1.7.1/lib/Twig_Function.php) for handling different Twig versions. So instead of writing:

```php
$twig->addFunction( new \Twig_Function( 'Product', function( $pid ) {
```

could you try using

```php
$twig->addFunction( new \Timber\Twig_Function( 'Product', function( $pid ) {
```

and see if you still run into the error?

**Comment by pelmered** [comment]
Why is this not merged? This package is useless without this fix.

**Comment by pelmered** [comment]
`\Timber\Twig_Function` works for me.

**Comment by gchtr** [comment]
Closing this, because it was solved by #5. Sorry for the longer wait!

**Pull request closed without merging**
